import { useEffect, useState } from 'react'
import { DialogContent, DialogDescription, DialogRoot, DialogTitle } from '@/components/ui/dialog'
import { emitMvlTelemetry } from './mvl-telemetry'

export type GraphBuildCounts = { nodes: number; edges: number; constraints: number }
const stages = ['parse', 'extract', 'resolve', 'build'] as const
export function GraphBuilderPanel({ extractionReady, building, counts, error, onBuild, onRetry, onRollback }: { extractionReady: boolean; building: boolean; counts: GraphBuildCounts; error?: string | null; onBuild: () => void; onRetry?: () => void; onRollback?: () => void }) {
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [elapsed, setElapsed] = useState(0)
  const [stage, setStage] = useState(0)
  useEffect(() => { if (!building) return; const started = Date.now(); const timer = window.setInterval(() => { setElapsed(Date.now() - started); setStage((value) => Math.min(stages.length - 1, Math.floor((Date.now() - started) / 1000))) }, 500); return () => window.clearInterval(timer) }, [building])
  const confirm = () => { emitMvlTelemetry('build.started', { tenantId: 'current-tenant', workspaceId: 'current-workspace', graphRef: 'tender-sensitive', graphVersion: 'candidate', graphHash: 'pending', locale: 'en' }); setConfirmOpen(false); onBuild() }
  return <section aria-label="Graph builder" className="rounded-xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">Build candidate graph</h2><p className="mt-1 text-xs text-muted-foreground">Explicit build confirmation keeps candidate artifacts reversible.</p></div><button type="button" disabled={!extractionReady || building} onClick={() => setConfirmOpen(true)} className="h-8 rounded-full border px-3 text-xs font-medium focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary">{building ? 'Building…' : 'Build candidate graph'}</button></div><div className="mt-3 flex gap-3 text-xs text-muted-foreground"><span>{counts.nodes} nodes</span><span>{counts.edges} edges</span><span>{counts.constraints} constraints</span></div>{building ? <div aria-label="Build stages" className="mt-4 flex items-center gap-2 text-xs">{stages.map((name, index) => <span key={name} className={index === stage ? 'rounded-md bg-primary px-2 py-1 text-primary-foreground' : 'rounded-md border px-2 py-1'}>{name}</span>)}<span className="ml-auto tabular-nums">{(elapsed / 1000).toFixed(1)}s</span></div> : null}{error ? <div role="alert" className="mt-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-xs">{error}<button type="button" className="ml-2 underline" onClick={onRetry}>Retry</button><button type="button" className="ml-3 underline" onClick={onRollback}>Rollback to extraction list</button></div> : null}<DialogRoot open={confirmOpen} onOpenChange={setConfirmOpen}><DialogContent><div className="space-y-4 p-5"><DialogTitle>Confirm candidate graph build</DialogTitle><DialogDescription>Estimated output from the reviewed extraction list.</DialogDescription><dl className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-md border p-2"><dt>Nodes</dt><dd className="font-semibold">{counts.nodes}</dd></div><div className="rounded-md border p-2"><dt>Edges</dt><dd className="font-semibold">{counts.edges}</dd></div><div className="rounded-md border p-2"><dt>Constraints</dt><dd className="font-semibold">{counts.constraints}</dd></div></dl><button type="button" className="h-8 w-full rounded-md bg-primary text-xs text-primary-foreground" onClick={confirm}>Confirm build</button></div></DialogContent></DialogRoot></section>
}
